### ISSUE TITLE
Unused Import warnings

### ISSUE THREAD

**Issue by KyleErwin** [cirg-up/cilib-tutorial#4]
Looking at the latest release you'll see that during the compilation of the pdf tut runs into some import warnings.
Looking at the src code vs the pdf you'll see that even in blocks were an import statement isn't used it still produces an unused import warning. This lead me to believe that perhaps the warning is carrying over from previous tut blocks. But this isn't the case. I looked at previous tut blocks with no imports and they produced no warnings.

Import statements them selves are either in `:invisible` or `: silent` which prevent output. However it looks like some tut:book blocks are causing these warnings. I cant really identify what is causing this. Import statements them selves are either in `:invisible` or `: silent` which prevent output. Perhaps its thee way its compiled. My reasoning for this is if you look at the first import seen in the book causes this as well.

Perhaps we can suppress these warnings in tut by modifying this line of code? 
`scalacOptions in Tut := (scalacOptions in Tut).value.filterNot(Set("-Ywarn-unused-import"))`
I would prefer not to completely remove imports from blocks as they indicate to the reader what is required in order to use the section. Thoughts @gpampara ?

**Comment by gpampara** [comment]
You're right. The option needs to be filtered out in the build., but it's already present:

https://github.com/cirg-up/cilib-tutorial/blob/master/build.sbt#L25
